FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies, and specific Chrome/ChromeDriver versions.
RUN apt-get update -qq -y && \
    apt-get install -y --no-install-recommends \
        libasound2 \
        libatk-bridge2.0-0 \
        libgtk-4-1 \
        libnss3 \
        xdg-utils \
        wget \
        unzip \
        && rm -rf /var/lib/apt/lists/*

# Download and install specific Chrome version (121.0.6167.85).  Using bit.ly is generally
# not a great practice for production, as it's an opaque redirect.  Ideally,
# find the direct Google download URL.  But this will work for this specific case.
RUN wget -q -O chrome-linux64.zip https://bit.ly/chrome-linux64-121-0-6167-85 && \
    unzip chrome-linux64.zip && \
    rm chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome/ && \
    ln -s /opt/chrome/chrome /usr/local/bin/

# Download and install *matching* ChromeDriver version (121.0.6167.85)
RUN wget -q -O chromedriver-linux64.zip https://bit.ly/chromedriver-linux64-121-0-6167-85 && \
    unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver && \
    rm chromedriver-linux64.zip && \
    mv chromedriver /usr/local/bin/

WORKDIR /app
RUN git clone https://github.com/OisinHick/The-Advanced-Cartographer.git /app

# Install Python dependencies. Since we are manually installing ChromeDriver,
# remove webdriver-manager.  It's crucial that the Chrome and ChromeDriver
# versions match EXACTLY.
RUN pip install bs4 selenium webdriver_manager requests

# Set the Chrome options to use the manually installed Chrome
CMD ["python", "/app/HaloCEMapDownloader.py", "-dm"]
#CMD ["bash", "-c", "tail -f /dev/null"]
